### ISSUE TITLE
Place type

### ISSUE THREAD

**Issue by sachinrv** [karamsa/GooglePlaceAutoComplete#2]
Thanks a lot for this plugin. Although I am facing one issue. I would like to get the location list for one particular city, how can I achieve this ?? 
For eg : I want all the location available in Banaglore, India.

**Comment by karamsa** [comment]
Hi sachinrv,
Thanks for your feedback, 
For your question, I thinks as i knew you can't get a list of locations by giving a city, but you can find all addresses that start for example with "pari" and you will get all addresses that contains "pari". for this you should replace in your code: 
whatever:type="(cities)" by whatever:type="address"
