### ISSUE TITLE
Is it possible to change the color of the text in predictions box?

### ISSUE THREAD

**Issue by vansh1sh** [karamsa/GooglePlaceAutoComplete#6]

**Comment by karamsa** [comment]
Hello, Thank you for using this module.
Yes you can changing the background of the dropdown box by xml:
add this to <co.geeksters.googleplaceautocomplete.lib.CustomAutoCompleteTextView>
android:popupBackground="#ff0000"

**Comment by vansh1sh** [comment]
Thanks! That did help. How to change the Text color inside the Popup?

**Comment by karamsa** [comment]
You can change the color of an the items in the dropdown of the autocomplete by doing that in your adapter 

` @Override
public View getView(int position, View v, ViewGroup parent)
{
    View mView = v ;
    if(mView == null){
        LayoutInflater vi = (LayoutInflater)appContext.getSystemService(Context.LAYOUT_INFLATER_SERVICE);
        mView = vi.inflate(id, null);
    }
    TextView text = (TextView) mView.findViewById(R.id.textview);        
    text.setTextColor(Color.parseColor("#999999"));
    text.setText("set some text");               
    return mView;
}    `
